version: '3.7'
services:

  # Nginx server
  weather-forecast-nginx-server:
    container_name: weather-forecast-nginx-server
    build:
      context: .    
      dockerfile: ./docker/nginx-server/Dockerfile
    restart: always
    ports:
      - 8181:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx-server/etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - php-server

  # PHP server
  weather-forecast-php-server:
    container_name: weather-forecast-php-server
    build:
      context: .        
      dockerfile: ./docker/php-server/Dockerfile
    restart: always
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

